[toolchain]
# channel = "1.75.0"
#channel = "1.80.0"
# rustup install nightly
channel = "nightly-2025-04-21" # if you want to expand the macro, you need to use nightly version
#components = ["rustfmt", "clippy"]
